String gitCredentials = "MyGitHub"
String dockerHubCredentials = "MyDockerHub"
String repoUrl = "https://github.com/warhunt/hello-app.git"
String ciRepoUrl = "https://github.com/warhunt/hello-app-cicd.git"
String branchName = "staging"
pipeline {
    agent any 
    options {
        skipDefaultCheckout(true)
    }
    stages {
        stage('Build') { 
            steps {
                echo 'Cloning files from (branch: "' + branchName + '" )'
                git branch: branchName, credentialsId: gitCredentials, url: repoUrl

                dir('ci') {
                    echo 'Cloning files from ci'
                    git branch: 'master', credentialsId: gitCredentials, url: ciRepoUrl

                    fileOperations([fileCopyOperation(
                        excludes: 'staging/Jenkinsfile',
                        flattenFiles: true,
                        includes: "staging/*",
                        targetLocation: "${WORKSPACE}/"
                    )])
                }
                
                script {
                    dockerImage = docker.build "wolly8898/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"

                    docker.withRegistry('', dockerHubCredentials ) { 
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }

        }
        //stage('Deploy'){
        //    steps {

        //    }
        //}
        //stage('Remove Unused docker image') {
        //    steps{
        //    sh "docker rmi $DOCKER_IMAGE_NAME:$BUILD_NUMBER"
        //    sh "docker rmi $DOCKER_IMAGE_NAME:latest"
        //    }
        //}
    }
}