---
  - hosts: app
    become: true
    become_user: vagrant
    tasks:
      - name: Copy Docker Image
        copy:
          src: "{{ path_docker_image }}"
          dest: "{{ dest_docker_image }}"

      - name: Load image from archive
        docker_image:
          name: "{{ docker_image_name }}"
          tag: "{{ docker_image_tag }}"
          load_path: "~/container.tar"
          source: load

      - name: Restart a container
        docker_container:
          name: "{{ app_name }}"
          image: "{{ docker_image_name }}:{{ docker_image_tag }}"
          state: started
          restart: yes
          ports:
            - "8080:{{ app_port }}"
          